# Syst√®me de likes remis ici pour que cela fonctionne avec le prefixe /ponthub
upont_api_ponthub_filelist:
    pattern: /filelist/{token}
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::filelistAction }
    requirements:
        _method: POST

upont_api_ponthub_gracenote:
    pattern: /gracenote
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::gracenoteAction }
    requirements:
        _method: POST

upont_api_ponthub_imdb_search:
    pattern: /imdb/search
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::imdbSearchAction }
    requirements:
        _method: POST

upont_api_ponthub_imdb_infos:
    pattern: /imdb/infos
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::imdbInfosAction }
    requirements:
        _method: POST

upont_api_ponthub_search:
    pattern: /search
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::searchAction }
    requirements:
        _method: POST

upont_api_ponthub_statistics_general:
    pattern: /ponthub/statistics
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::statisticsMainAction }
    requirements:
        _method: GET

upont_api_ponthub_statistics:
    pattern: /ponthub/statistics/{slug}
    defaults: { _controller: KI\PonthubBundle\Controller\DefaultController::statisticsAction }
    requirements:
        _method: GET


# Ressources REST

albums:
    type:     rest
    resource: KI\PonthubBundle\Controller\AlbumsController

games:
    type:     rest
    resource: KI\PonthubBundle\Controller\GamesController

movies:
    type:     rest
    resource: KI\PonthubBundle\Controller\MoviesController

others:
    type:     rest
    resource: KI\PonthubBundle\Controller\OthersController

softwares:
    type:     rest
    resource: KI\PonthubBundle\Controller\SoftwaresController

requests:
    type:     rest
    resource: KI\PonthubBundle\Controller\RequestsController

series:
    type:     rest
    resource: KI\PonthubBundle\Controller\SeriesController
