parameters:
    # Liste les entit√©s likeables
    likeables:
        clubinfo:
            - Fix
            - Tuto
        core:
            - Comment
        foyer:
            - Beer
            - Youtube
        ponthub:
            - Episode
            - Game
            - Movie
            - Other
            - Request
            - Serie
            - Software
        publication:
            - Course
            - Event
            - Exercice
            - Newsitem
        user:
            - Club
            - Experience
            - User
