security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MODO:       [ROLE_USER, ROLE_JARDINIER]
        ROLE_ADMIN:      [ROLE_MODO, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # Proc√©dure de login
        login:
            pattern:  ^/login$
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: username
                password_parameter: password

        login_sso:
            pattern: ^/login/sso$
            stateless: true
            anonymous: true
            trusted_sso:
                manager: enpc_sso
                login_action: BeSimpleSsoAuthBundle:TrustedSso:login
                logout_action: BeSimpleSsoAuthBundle:TrustedSso:logout
                create_users: true
                created_users_roles: [ROLE_USER]

        ping:
            methods: [GET, HEAD]
            pattern: ^/ping
            security: false

        resetting:
            methods: [POST]
            pattern: ^/resetting
            security: false

        download:
            methods: [GET]
            pattern: ^/courses/.+/exercices/.+/download
            security: false

        calendar:
            methods: [GET]
            pattern: ^/users/.+/calendar
            security: false

        # Firewall principal
        api:
            pattern:   ^/.+
            switch_user: { parameter: _nsa }
            stateless: true
            anonymous: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix: Bearer
                query_parameter:
                    enabled: true
                    name: bearer

    access_control:
        - { path: ^/(clubs)(/[a-zA-Z]+)?,             methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,                            methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/sso,                            methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ping,                             methods: [HEAD, GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/courses,                          methods: [HEAD], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_(profiler|wdt|doc))/,           methods: [GET],  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coffee,                           methods: [GET],  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/version,                          methods: [GET],  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admissibles,                      methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/baskets/.+/order,                 methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/baskets,                          methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/filelist,                         methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users,                            methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^, roles: IS_AUTHENTICATED_FULLY }
